project_id = "bklfolfivjonzpprytkz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.detect-unusual-access]
verify_jwt = true

[functions.finny-chat]
verify_jwt = true

[functions.reset-password-page]
verify_jwt = false

[functions.send-password-reset-code]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.update-password-with-code]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false