
project_id = "bklfolfivjonzpprytkz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.finny-chat]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true
